config/routes.rb
Rails.application.routes.draw do
  draw(:pwa)
  devise_for :users

  resources :favorites
  resources :comments
  resources :jobs

  get "in/:username", to: "in#show", as: :in

  unauthenticated do
    root "page#landing"
  end

  authenticated :user do
    root "jobs#index", as: :authenticated_root
  end
end

app/models/concerns/job/ransackable.rb
module Job::Ransackable
  extend ActiveSupport::Concern

  class_methods do
    def ransackable_attributes(auth_object = nil)
      ["category", "description", "title"]
    end

    def ransackable_associations(auth_object = nil)
      []
    end
  end
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id          :bigint           not null, primary key
#  category    :string
#  deadline    :date
#  description :string
#  link        :string
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#
class Job < ApplicationRecord
  include Ransackable

  belongs_to :user, required: true, class_name: "User", foreign_key: "user_id"

  scope :default_order, -> { order(deadline: :asc) }
  scope :upcoming, -> { where(deadline: Date.today..) }

  validates :title, presence: true
  validates :category, presence: true

  # TODO: add enum for category so it can be a dropdown

  def to_s
    "#{title} (#{category})"
  end


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @breadcrumbs = [
      {content: "Jobs"}
    ]
    @q = Job.ransack(params[:q])
    @jobs = @q.result.default_order.page(params[:page]).per(10)
  end

  def show
    @job = Job.find(params[:id])
    @breadcrumbs = [
      {content: "Jobs", href: jobs_path},
      {content: @job}
    ]
  end

  def new
    @breadcrumbs = [
      {content: "Jobs", href: jobs_path},
      {content: "New"}
    ]
    @job = current_user.jobs.new
  end

  def create
    @job = current_user.jobs.new(job_params)

    if @job.save
      redirect_to(job_path(@job), notice: "Job created successfully.")
    else
      flash[:alert] = @job.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @job = Job.find(params[:id])
    @breadcrumbs = [
      {content: "Jobs", href: jobs_path},
      {content: @job, href: job_path(@job)},
      {content: "Edit"}
    ]
  end

  def update
    @job = Job.find(params[:id])

    if @job.update(job_params)
      redirect_to(job_path(@job), notice: "Job updated successfully.")
    else
      flash[:alert] = @job.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    job = Job.find(params.fetch("id"))
    job.destroy

    redirect_to(jobs_path, notice: "Job deleted successfully.")
  end

  private

  def job_params
    params.require(:job).permit(:title, :link, :description, :deadline, :category)
  end

end

app/views/jobs/_form.html.erb
<%= form_with model: job do |form| %>

  <div class="my-2">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="my-2">
    <%= form.label :link, class: "form-label" %>
    <%= form.text_field :link, class: "form-control" %>
  </div>

  <div class="my-2">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="my-2">
    <%= form.label :category, class: "form-label" %>
    <%= form.text_field :category, class: "form-control" %>
  </div>

  <div class="my-2">
    <%= form.label :deadline, class: "form-label" %>
    <%= form.date_field :deadline, class: "form-control" %>
  </div>

  <div class="my-2">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/jobs/_list_group.html.erb
<div class="list-group list-group-flush">
  <% jobs.each do |job| %>
    <%= link_to job, class: "list-group-item list-group-item-action" do %>
      <h5>
        <%= job %>
      </h5>
      <p>
        <%= job.description.truncate_words(5) %>
      </p>
    <% end %>
  <% end %>
</div>

app/views/jobs/_search.html.erb
<%= search_form_for q do |f| %>

  <div class="input-group">
    <%= f.label :title_or_category_or_description_cont, "Search", class: "visually-hidden" %>
    <%= f.search_field :title_or_category_or_description_cont, placeholder: "Job title, category, or description", class: "form-control rounded-start-2", autofocus: true %>
    <%= f.submit "Search", class: "btn btn-primary" %>
    <a href="/jobs" class="btn btn-outline-secondary">Clear</a>
  </div>
  
<% end %>

app/views/jobs/edit.html.erb
<div class="card">

  <div class="card-header">
    <h1>Edit job</h1>
  </div>

  <div class="card-body">
    <%= render "form", job: @job %>
  </div>
    
</div>

app/views/jobs/index.html.erb
<div class="container px-0 my-2">
  <div class="card">
    <div class="card-header">
      <div class="d-flex justify-content-between align-items-center">
        <h1>List of jobs</h1>

        <%= link_to new_job_path do %>
          <i class="fa-regular fa-square-plus fa-2x"></i>
        <% end %>
      </div>

      <div class="mb-2">
        <%= render "search", q: @q %>
      </div>
    </div>
    <%= render "jobs/list_group", jobs: @jobs %>
    <div class="card-footer text-body-secondary">
      <%= paginate @jobs %>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="card">

  <div class="card-header">
    <h1>Add a new job</h1>
  </div>

  <div class="card-body">
    <%= render "form", job: @job %>
  </div>

</div>

app/views/jobs/show.html.erb
<div class="container px-0 my-2">
  <div class="card">
    <div class="card-header">
      <div class="d-flex justify-content-between align-items-center">
        <h1>
          <%= @job %>
        </h1>

        <div class="d-flex align-items-center">
          <%= link_to edit_job_path(@job) do %>
            <i class="fa-solid fa-pen-to-square fa-2x text-secondary"></i>
          <% end %>
          <%= button_to(job_path(@job), class: "btn btn-link", method: :delete, data: { confirm: "Are you sure?" }) do %>
            <i class="fa-solid fa-trash fa-2x text-danger"></i>
          <% end %>
        </div>
      </div>
    </div>

    <div class="card-body">
      <p class="card-text">
        <dl>
          <dt>
            Title
          </dt>
          <dd>
            <%= @job.title %>
          </dd>

          <dt>
            Link
          </dt>
          <dd>
            <%= @job.link %>
          </dd>

          <dt>
            Description
          </dt>
          <dd>
            <%= @job.description %>
          </dd>

          <dt>
            Deadline
          </dt>
          <dd>
            <%= @job.deadline %>
          </dd>

          <dt>
            User
          </dt>
          <dd>
            <div class="row">
              <div class="col-md-3 text-center">
                <%= link_to in_path(@job.user.username), class: "text-decoration-none text-dark" do %>
                  <% if @job.user.avatar.attached? %>
                    <%= image_tag(@job.user.avatar, alt: @job.user.username, class: "img-fluid rounded-circle mb-3") %>
                  <% end %>
                  <h2><%= @job.user.username %></h2>
                <% end %>
              </div>
            </div>
          </dd>

          <dt>
            Category
          </dt>
          <dd>
            <%= @job.category %>
          </dd>

          <dt>
            Created at
          </dt>
          <dd>
            <%= time_ago_in_words(@job.created_at) %> ago
          </dd>

          <dt>
            Updated at
          </dt>
          <dd>
            <%= time_ago_in_words(@job.updated_at) %> ago
          </dd>
        </dl>
      </p>
    </div>

    
  </div>
</div>